### ISSUE TITLE
Лицензия GNU GPL 3.0

### ISSUE THREAD

**Issue by OsipXD** [TheQmaks/ReflectionAPI#1]
Привет. Проект нарушает лицензию, под которой предоставляется. А именно тот её пункт в котором сказано, что каждый файл исходников должен содержать копирайт и информацию о лицензии.
https://www.gnu.org/licenses/gpl-howto.html

Формальность, но необходимая

**Comment by OsipXD** [comment]
Хотя подобные утилитки на один класс вообще удобнее делать в виде Gist'а

**Comment by TheQmaks** [comment]
Как оказалось - не надо. Информация есть в файлике LICENSE, чего как оказалось - достаточно.

**Comment by OsipXD** [comment]
Нет, лицензия требует содержания копирайта и информации о лицензии в каждом файле исходного кода. Это написано по ссылке которую я кинул выше, а это официальный источник.
